version = "2"
generators = ["go", "go-ttrpc"]


# Control protoc include paths. Below are usually some good defaults, but feel
# free to try it without them if it works for your project.
[includes]
  # Include paths that will be added before all others. Typically, you want to
  # treat the root of the project as an include, but this may not be necessary.
  before = ["/local/home/sbora/TTRPC/ttrpc/contrib/otelttrpc/otelexample/"]

  # Paths that will be added untouched to the end of the includes. We use
  # `/usr/local/include` to pickup the common install location of protobuf.
  # This is the default.
  after = ["/usr/local/include", "/usr/include"]

# This section maps protobuf imports to Go packages. These will become
# `-M` directives in the call to the go protobuf generator.
[packages]
  "google/rpc/status.proto" = "github.com/containerd/containerd/protobuf/google/rpc"
